### ISSUE TITLE
pyXAI GUI crashing on Debian 12

### ISSUE THREAD

**Issue by gildasmorvan** [crillab/pyxai#3]
# pyXAI GUI crashes on Debian 12 under virtualBox

Here is the log:
```
Python version:  3.11.2
PyXAI version:  1.0.8

PyXAI location:  /home/morvan/learn_and_explain_agent_based_models/lib/python3.11/site-packages/pyxai
Traceback (most recent call last):
  File "/home/morvan/learn_and_explain_agent_based_models/lib/python3.11/site-packages/pyxai/sources/core/tools/GUIQT.py", line 206, in mouseMoveEventLeft
    if self.pressed:
       ^^^^^^^^^^^^
AttributeError: 'GraphicalInterface' object has no attribute 'pressed'
  ``

**Comment by gildasmorvan** [comment]
Add `self.pressed = False` in `__init__` method of [GUIQT.py ](https://github.com/crillab/pyxai/blob/main/pyxai/sources/core/tools/GUIQT.py) seems to solve the problem.

**Comment by szczepanskiNicolas** [comment]
Hello, Thank you very much for discovering this problem.  

I have installed Debian GNU/Linux 12 (bookworm) with Gnome and Python 3.11.2. 
Which desktop environment do you use? Because I haven't had any problems with my configuration.
![image](https://github.com/crillab/pyxai/assets/29594602/51f78efc-5d1b-430f-967c-d75e7e7ac478)

But yes, `self.pressed` should have been initialized. Thank you for your contribution.

**Comment by gildasmorvan** [comment]
Hi, I use gnome (the default environment).

**Comment by gildasmorvan** [comment]
Hi @szczepanskiNicolas, problem seems solved indeed!
